### ISSUE TITLE
Wie kann man DDP neu installieren/deinstallieren?

### ISSUE THREAD

**Issue by marlester-dev** [DDP-Projekt/Kompilierer#88]
Windows

**Comment by bafto** [comment]
1. Wenn du DDP updaten möchtest: siehe https://ddp.le0n.dev/Bedienungsanleitung/de/Einstieg/Updates/
2. Falls das nicht klappt oder um DDP zu deinstallieren einfach den Installations Ordner löschen. Um alles komplett aufzuräumen auch noch die Umgebungsvariable "DDPPATH" löschen und den <ddp-installations-pfad>/bin Ordner aus der PATH Umgebungsvariable entfernen
